name: build

on:
  push:
    branches: [main]

jobs:
  dist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, chrome]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci --prefer-offline --no-audit
      - run: npm run build-${{ matrix.browser }}
      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.browser }}
          path: dist/
          if-no-files-found: error
